version: "3"

services:
  db:
    image: postgres:14.9-alpine
    restart: always
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_PASSWORD=task
      - POSTGRES_USER=task
      - POSTGRES_DB=task  
  rabbit:
    image: rabbitmq:3.13-rc-management
    restart: always
    ports:
      - "15672:15672/tcp"
      - "5672:5672/tcp"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  task:
    depends_on:
      - db
    build: .
    deploy:
      mode: replicated
      replicas: 6
    restart: always
