version: "3"

services:
  db:
    image: postgres:14.9-alpine
    restart: always
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_PASSWORD=task
      - POSTGRES_USER=task
      - POSTGRES_DB=task
  rabbit:
    image: rabbitmq:3.13-rc-management
    restart: always
    ports:
      - "15672:15672/tcp"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  router:
    depends_on:
      - db
      - rabbit
    build:
      dockerfile: ./router/Dockerfile
    ports:
      - "8080:8080/tcp"
    restart: always
  task:
    depends_on:
      - db
      - rabbit
      - router
    build:
      dockerfile: ./app/Dockerfile
    deploy:
      mode: replicated
      #replicas: ${REPLICA_COUNT}
    restart: always
